### ISSUE TITLE
Failed to Get AI Response

### ISSUE THREAD

**Issue by Niansuh** [devnamdev2003/chatBot#4]
### Dear Sir,

I am writing to inform you that I am experiencing an error when testing the chat feature. The error message is "Failed to Get AI Response." I have tried restarting the chat and refreshing the page, but the error persists.

I would appreciate it if you could investigate this issue and provide me with a code to resolve it.

Thank you for your time and attention to this matter.
Email: niansuhtech@gmail.com

Sincerely,
Husnain Rasheeed

**Comment by devnamdev2003** [comment]
but When I saw it, it was working very well.

**Comment by gumnaampk** [comment]
can you send me a comined code in single file please sir

**Comment by gumnaampk** [comment]
Sir Please Provide Me Code In Single File

**Comment by gumnaampk** [comment]
when i test the chatbot its showing error failed to get ai response.

**Comment by gumnaampk** [comment]
> but When I saw it, it was working very well.


can you send me a comined code in single file please sir

**Comment by devnamdev2003** [comment]
https://github.com/devnamdev2003/chatBot/archive/refs/heads/main.zip
